/*
 * Copyright (c) 2014-2016 Cesanta Software Limited
 * All rights reserved
 */

#ifndef CS_SMARTJS_PLATFORMS_ESP8266_USER_V7_ESP_FEATURES_H_
#define CS_SMARTJS_PLATFORMS_ESP8266_USER_V7_ESP_FEATURES_H_
#endif /* CS_SMARTJS_PLATFORMS_ESP8266_USER_V7_ESP_FEATURES_H_ */
