FROM ubuntu:bionic-20190807

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -q \
      apt-utils autoconf bison build-essential flex gawk gdb-multiarch git gperf help2man \
      libexpat-dev libncurses5-dev libtool-bin \
      python python-dev python-git python-pyelftools python-serial python-six python-yaml \
      python3 python3-dev python3-git python3-pyelftools python3-serial python3-six python3-yaml \
      software-properties-common texinfo unzip wget zip && \
    apt-get clean

RUN cd /tmp && \
    git clone https://github.com/rojer/fsync-stub && \
    cd /tmp/fsync-stub && ./install.sh && \
    rm -rf /tmp/fsync-stub

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -q \
      python-click python3-click \
      python-cryptography python3-cryptography \
      python-future python3-future \
      python-pkg-resources python3-pkg-resources \
      python-pyparsing python3-pyparsing \
      python-setuptools python3-setuptools \
      python-pip python3-pip \
      rsync && \
    apt-get clean

RUN pip install reedsolo bitstring ecdsa

RUN useradd -d /opt/Espressif -m -s /bin/bash user && chown -R user /opt

ARG TOOLCHAIN_VERSION
RUN cd /opt/Espressif && wget -q https://dl.espressif.com/dl/$TOOLCHAIN_VERSION.tar.gz && \
    tar xzf $TOOLCHAIN_VERSION.tar.gz && \
    rm $TOOLCHAIN_VERSION.tar.gz
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/Espressif/xtensa-esp32-elf/bin
ADD ct_path.sh /etc/profile.d

ARG DOCKER_TAG
RUN git clone -j 8 --branch $DOCKER_TAG --depth 1 --recursive --shallow-submodules https://github.com/mongoose-os/esp-idf /opt/Espressif/esp-idf
RUN cd /opt/Espressif/esp-idf && git tag v$DOCKER_TAG
ENV IDF_PATH=/opt/Espressif/esp-idf

# Apply submodule patches.
RUN cd $IDF_PATH && ./patch_submodules.sh

# Pre-build configuration tools
RUN cd $IDF_PATH/tools/kconfig && make conf-idf

ADD rom.bin rom.elf /opt/Espressif/rom/

ADD mgos_fw_meta.py mklfs mkspiffs mkspiffs8 /usr/local/bin/
ADD serve_core/ /opt/serve_core/
RUN ln -s /opt/serve_core/serve_core.py /usr/local/bin/serve_core.py

ARG DOCKER_TAG
ENV MGOS_TARGET_GDB /opt/Espressif/xtensa-esp32-elf/bin/xtensa-esp32-elf-gdb
ENV MGOS_SDK_REVISION $DOCKER_TAG
ENV MGOS_SDK_BUILD_IMAGE docker.io/mgos/esp32-build:$DOCKER_TAG
