#ifndef __CONFIG_H_
#define __CONFIG_H_

#define CONSOLE_BAUD_RATE 115200
#define CONSOLE_UART UARTA0_BASE
#define CONSOLE_UART_INT INT_UARTA0
#define CONSOLE_UART_PERIPH PRCM_UARTA0

#endif /* __CONFIG_H_ */
