FROM ubuntu:xenial

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -q \
      apt-utils autoconf bison build-essential flex gawk git gperf help2man \
      libexpat-dev libncurses5-dev libtool-bin \
      python python-dev python-git python-pyelftools python-serial python-six python-yaml \
      software-properties-common texinfo unzip vim-nox wget zile zip && \
    apt-get clean

RUN cd /tmp && \
    git clone https://github.com/rojer/fsync-stub && \
    cd /tmp/fsync-stub && ./install.sh && \
    rm -rf /tmp/fsync-stub

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -q \
      gcc-arm-none-eabi gdb-arm-none-eabi libnewlib-arm-none-eabi libnewlib-dev && \
    apt-get clean

RUN cd /tmp && \
    git clone https://github.com/rojer/fsync-stub && \
    cd /tmp/fsync-stub && ./install.sh && \
    rm -rf /tmp/fsync-stub

ARG TI_COMPILER_DIR
ADD $TI_COMPILER_DIR /opt/$TI_COMPILER_DIR

# Create our own version of libc - with no HOSTIO and malloc functions.
ADD ti_libc.patch /opt/$TI_COMPILER_DIR/lib
RUN cd /opt/$TI_COMPILER_DIR/lib && rm *.lib && \
    patch -p 0 < ti_libc.patch && \
    ./mklib --index=libc.a --pattern=rtsv7M4_T_le_eabi.lib \
            --extra_options='-O4 --opt_for_speed=0' \
            --compiler_bin_dir=../bin \
            --name=rtsv7M4_T_le_eabi_cesanta.lib --install_to=. \
            --parallel=4

ARG SDK_DIR
ADD $SDK_DIR /opt/$SDK_DIR
ADD user.h /opt/$SDK_DIR/source/ti/drivers/net/wifi/porting/user.h
# There is List.c in the SDK and then there's list.c in FreeRTOS.
# MacOS, in its infinite wisdom, confuses the two. Hilarity ensues.
RUN mv /opt/$SDK_DIR/source/ti/drivers/utils/List.c \
       /opt/$SDK_DIR/source/ti/drivers/utils/ListUtils.c

RUN cd /opt && \
    wget -q http://www.realtimeengineers.com/ReferencedDownloads/170425_FreeRTOS_SimpleLink_CC3220SF_CCS.zip && \
    unzip -q 170425_FreeRTOS_SimpleLink_CC3220SF_CCS.zip && \
    rm 170425_FreeRTOS_SimpleLink_CC3220SF_CCS.zip

ADD fw_meta.py serve_core.py mklfs mkspiffs mkspiffs8 /usr/local/bin/

ENV SDK_PATH=/opt/$SDK_DIR
ENV TI_COMPILER_PATH=/opt/$TI_COMPILER_DIR
ENV FREERTOS_PATH=/opt/FreeRTOS_SimpleLink_CC3220SF_CCS/FreeRTOS
ENV MGOS_TARGET_GDB=/usr/bin/arm-none-eabi-gdb
