ARG DOCKER_TAG
FROM docker.io/mgos/esp8266-toolchain:$DOCKER_TAG

ADD cs_mbedtls /opt/cs_mbedtls

ARG DOCKER_TAG
ENV MGOS_SDK_REVISION $DOCKER_TAG
ENV MGOS_SDK_BUILD_IMAGE docker.io/mgos/esp8266-build:$DOCKER_TAG
