// Code generated by "stringer -type=transport transport.go"; DO NOT EDIT

package mgrpc

import "fmt"

const _transport_name = "tHTTP_POSTtWebSockettPlainTCPtSerial"

var _transport_index = [...]uint8{0, 10, 20, 29, 36}

func (i transport) String() string {
	if i < 0 || i >= transport(len(_transport_index)-1) {
		return fmt.Sprintf("transport(%d)", i)
	}
	return _transport_name[_transport_index[i]:_transport_index[i+1]]
}
