/*
 * Copyright (c) 2014-2016 Cesanta Software Limited
 * All rights reserved
 */

#ifndef CS_FW_SRC_MGOS_DEPS_H_
#define CS_FW_SRC_MGOS_DEPS_H_

#include "fw/src/mgos_features.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/*
 * Dependencies initialization; implementation should typically be
 * autogenerated.
 */
bool mgos_deps_init(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CS_FW_SRC_MGOS_DEPS_H_ */
