/*
 * Copyright (c) 2014-2016 Cesanta Software Limited
 * All rights reserved
 */

#ifndef CS_FW_SRC_MIOT_FEATURES_H_
#define CS_FW_SRC_MIOT_FEATURES_H_

#ifndef MIOT_ENABLE_ADC_API
#define MIOT_ENABLE_ADC_API 0
#endif

#ifndef MIOT_ENABLE_RPC
#define MIOT_ENABLE_RPC 0
#endif

#ifndef MIOT_ENABLE_RPC_CHANNEL_HTTP
#define MIOT_ENABLE_RPC_CHANNEL_HTTP 0
#endif

#ifndef MIOT_ENABLE_CONSOLE_FILE_BUFFER
#define MIOT_ENABLE_CONSOLE_FILE_BUFFER 0
#endif

#ifndef MIOT_ENABLE_DEBUG_API
#define MIOT_ENABLE_DEBUG_API 0
#endif

#ifndef MIOT_ENABLE_DNS_SD
#define MIOT_ENABLE_DNS_SD 0
#endif

#ifndef MIOT_ENABLE_FILE_UPLOAD
#define MIOT_ENABLE_FILE_UPLOAD 0
#endif

#ifndef MIOT_ENABLE_HTTP_CLIENT_API
#define MIOT_ENABLE_HTTP_CLIENT_API 0
#endif

#ifndef MIOT_ENABLE_HTTP_SERVER_API
#define MIOT_ENABLE_HTTP_SERVER_API 0
#endif

#ifndef MIOT_ENABLE_JS
#define MIOT_ENABLE_JS 0
#endif

#ifndef MIOT_ENABLE_MDNS
#define MIOT_ENABLE_MDNS 0
#endif

#ifndef MIOT_ENABLE_MQTT
#define MIOT_ENABLE_MQTT 0
#endif

#ifndef MIOT_ENABLE_MQTT_API
#define MIOT_ENABLE_MQTT_API 0
#endif

#ifndef MIOT_ENABLE_PWM_API
#define MIOT_ENABLE_PWM_API 0
#endif

#ifndef MIOT_ENABLE_SPI_API
#define MIOT_ENABLE_SPI_API 0
#endif

#ifndef MIOT_ENABLE_TCP_API
#define MIOT_ENABLE_TCP_API 0
#endif

#ifndef MIOT_ENABLE_UART_API
#define MIOT_ENABLE_UART_API 0
#endif

#ifndef MIOT_ENABLE_UDP_API
#define MIOT_ENABLE_UDP_API 0
#endif

#ifndef MIOT_ENABLE_UPDATER
#define MIOT_ENABLE_UPDATER 0
#endif

#ifndef MIOT_ENABLE_UPDATER_RPC
#define MIOT_ENABLE_UPDATER_RPC 0
#endif

#ifndef MIOT_ENABLE_UPDATER_POST
#define MIOT_ENABLE_UPDATER_POST 0
#endif

#ifndef MIOT_ENABLE_WEB_CONFIG
#define MIOT_ENABLE_WEB_CONFIG 0
#endif

#ifndef MIOT_ENABLE_WIFI
#define MIOT_ENABLE_WIFI 0
#endif

#ifndef MIOT_ENABLE_WIFI_API
#define MIOT_ENABLE_WIFI_API 0
#endif

#ifndef MIOT_ENABLE_WS_CLIENT_API
#define MIOT_ENABLE_WS_CLIENT_API 0
#endif

#ifndef MIOT_PROMPT_DISABLE_ECHO
#define MIOT_PROMPT_DISABLE_ECHO 0
#endif

#ifndef MIOT_ENABLE_HTTP_SERVER
#define MIOT_ENABLE_HTTP_SERVER 1
#endif

#endif /* CS_FW_SRC_MIOT_FEATURES_H_ */
