APP = c_mcast
APP_MODULES = src
APP_FS_PATH = fs
APP_CONF_SCHEMA = $(CURDIR)/src/conf_schema.yaml

# currently this example supports only esp8266
PLATFORM = esp8266

include $(REPO_PATH)/fw/platforms/$(PLATFORM)/Makefile.build
