FROM ubuntu:bionic-20190807

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -q \
      apt-utils autoconf automake bison build-essential curl flex gawk gdb-multiarch git gperf help2man \
      less libexpat-dev libncurses5-dev libtool-bin \
      python python-dev python-git python-pyelftools python-serial python-six python-yaml \
      python3 python3-dev python3-git python3-pyelftools python3-serial python3-six python3-yaml \
      software-properties-common texinfo unzip wget zip && \
    apt-get clean

RUN useradd -d /opt/Espressif -m -s /bin/bash user && chown -R user /opt

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/Espressif/esp-open-sdk/xtensa-lx106-elf/bin
ADD ct_path.sh /etc/profile.d

USER user

ARG DOCKER_TAG
RUN git clone -b $DOCKER_TAG --depth 1 https://github.com/mongoose-os/esp-open-sdk /opt/Espressif/esp-open-sdk && \
    cd /opt/Espressif/esp-open-sdk && \
    git submodule update --init && \
    nice make && rm -rf crosstool-ng

USER root

RUN ln -s /opt/Espressif/esp-open-sdk/sdk /opt/Espressif/ESP8266_NONOS_SDK

RUN cd /opt/Espressif/ESP8266_NONOS_SDK/lib && \
    xtensa-lx106-elf-ar -x libmain.a && \
    xtensa-lx106-elf-objcopy --weaken mem_manager.o && \
    xtensa-lx106-elf-ar -rc libmain.a *.o && \
    rm *.o

RUN xtensa-lx106-elf-objcopy \
      --weaken-symbol Cache_Read_Enable_New \
      --redefine-sym system_restart_local=system_restart_local_sdk \
      /opt/Espressif/ESP8266_NONOS_SDK/lib/libmain.a

RUN mv /opt/Espressif/ESP8266_NONOS_SDK/lib/libc.a /opt/Espressif/ESP8266_NONOS_SDK/lib/libc_sdk.a && \
    mv /opt/Espressif/ESP8266_NONOS_SDK/lib/libgcc.a /opt/Espressif/ESP8266_NONOS_SDK/lib/libgcc_sdk.a && \
    mv /opt/Espressif/ESP8266_NONOS_SDK/lib/libhal.a /opt/Espressif/ESP8266_NONOS_SDK/lib/libhal_sdk.a

ADD cs_lwip /opt/Espressif/cs_lwip
ADD rom.bin rom.elf /opt/Espressif/rom/

ADD mgos_fw_meta.py mklfs mkspiffs mkspiffs8 /usr/local/bin/
ADD serve_core/ /opt/serve_core/
RUN ln -s /opt/serve_core/serve_core.py /usr/local/bin/serve_core.py

ENV MGOS_TARGET_GDB=/opt/Espressif/esp-open-sdk/xtensa-lx106-elf/bin/xtensa-lx106-elf-gdb
ARG DOCKER_TAG
ENV MGOS_SDK_REVISION $DOCKER_TAG
ENV MGOS_SDK_BUILD_IMAGE docker.io/mgos/esp8266-build:$DOCKER_TAG
