APP = c_mdns
APP_MODULES = src
APP_FS_PATH = fs
MG_ENABLE_JS = 0
MG_ENABLE_CLUBBY = 1

# currently this example supports only esp8266
PLATFORM = esp8266

include $(REPO_PATH)/fw/platforms/$(PLATFORM)/Makefile.build
