// THIS FILE IS AUTOMATICALLY GENERATED, DO NOT MODIFY
// generated with: tools/genromsyms.py
// meant to be assembled with:
//     xt-as tools/romsyms.s -o tools/romsyms
// and loaded in gdb with:
//     add-symbol-file romsyms 0x40000000
  .section        .text,"ax",@progbits
  .literal_position
  .align  4
  .global _DebugExceptionVector
  .type   _DebugExceptionVector, @function
  .org    0x10
_DebugExceptionVector:
  .size   _DebugExceptionVector, 16

  .align  4
  .global _NMIExceptionVector
  .type   _NMIExceptionVector, @function
  .org    0x20
_NMIExceptionVector:
  .size   _NMIExceptionVector, 16

  .align  4
  .global _KernelExceptionVector
  .type   _KernelExceptionVector, @function
  .org    0x30
_KernelExceptionVector:
  .size   _KernelExceptionVector, 32

  .align  4
  .global _UserExceptionVector
  .type   _UserExceptionVector, @function
  .org    0x50
_UserExceptionVector:
  .size   _UserExceptionVector, 32

  .align  4
  .global _DoubleExceptionVector
  .type   _DoubleExceptionVector, @function
  .org    0x70
_DoubleExceptionVector:
  .size   _DoubleExceptionVector, 16

  .align  4
  .global _ResetVector
  .type   _ResetVector, @function
  .org    0x80
_ResetVector:
  .size   _ResetVector, 36

  .align  4
  .global _ResetHandler
  .type   _ResetHandler, @function
  .org    0xa4
_ResetHandler:
  .size   _ResetHandler, 904

  .align  4
  .global _start
  .type   _start, @function
  .org    0x42c
_start:
  .size   _start, 40

  .align  4
  .global _xtos_set_exception_handler
  .type   _xtos_set_exception_handler, @function
  .org    0x454
_xtos_set_exception_handler:
  .size   _xtos_set_exception_handler, 56

  .align  4
  .global _xtos_l1int_handler
  .type   _xtos_l1int_handler, @function
  .org    0x48c
_xtos_l1int_handler:
  .size   _xtos_l1int_handler, 224

  .align  4
  .global _xtos_restore_intlevel
  .type   _xtos_restore_intlevel, @function
  .org    0x56c
_xtos_restore_intlevel:
  .size   _xtos_restore_intlevel, 8

  .align  4
  .global _xtos_set_vpri
  .type   _xtos_set_vpri, @function
  .org    0x574
_xtos_set_vpri:
  .size   _xtos_set_vpri, 28

  .align  4
  .global _xtos_cause3_handler
  .type   _xtos_cause3_handler, @function
  .org    0x590
_xtos_cause3_handler:
  .size   _xtos_cause3_handler, 8

  .align  4
  .global _xtos_c_wrapper_handler
  .type   _xtos_c_wrapper_handler, @function
  .org    0x598
_xtos_c_wrapper_handler:
  .size   _xtos_c_wrapper_handler, 88

  .align  4
  .global srand
  .type   srand, @function
  .org    0x5f0
srand:
  .size   srand, 16

  .align  4
  .global rand
  .type   rand, @function
  .org    0x600
rand:
  .size   rand, 80

  .align  4
  .global __muldi3
  .type   __muldi3, @function
  .org    0x650
__muldi3:
  .size   __muldi3, 56

  .align  4
  .global xthal_bcopy
  .type   xthal_bcopy, @function
  .org    0x688
xthal_bcopy:
  .size   xthal_bcopy, 60

  .align  4
  .global xthal_memcpy
  .type   xthal_memcpy, @function
  .org    0x6c4
xthal_memcpy:
  .size   xthal_memcpy, 136

  .align  4
  .global xthal_copy123
  .type   xthal_copy123, @function
  .org    0x74c
xthal_copy123:
  .size   xthal_copy123, 200

  .align  4
  .global cmd_parse
  .type   cmd_parse, @function
  .org    0x814
cmd_parse:
  .size   cmd_parse, 264

  .align  4
  .global get_first_seg
  .type   get_first_seg, @function
  .org    0x91c
get_first_seg:
  .size   get_first_seg, 232

  .align  4
  .global remove_head_space
  .type   remove_head_space, @function
  .org    0xa04
remove_head_space:
  .size   remove_head_space, 92

  .align  4
  .global convert_para_str
  .type   convert_para_str, @function
  .org    0xa60
convert_para_str:
  .size   convert_para_str, 196

  .align  4
  .global conv_str_decimal
  .type   conv_str_decimal, @function
  .org    0xb24
conv_str_decimal:
  .size   conv_str_decimal, 404

  .align  4
  .global conv_str_hex
  .type   conv_str_hex, @function
  .org    0xcb8
conv_str_hex:
  .size   conv_str_hex, 264

  .align  4
  .global ets_set_idle_cb
  .type   ets_set_idle_cb, @function
  .org    0xdc0
ets_set_idle_cb:
  .size   ets_set_idle_cb, 16

  .align  4
  .global ets_task
  .type   ets_task, @function
  .org    0xdd0
ets_task:
  .size   ets_task, 52

  .align  4
  .global ets_run
  .type   ets_run, @function
  .org    0xe04
ets_run:
  .size   ets_run, 32

  .align  4
  .global ets_post
  .type   ets_post, @function
  .org    0xe24
ets_post:
  .size   ets_post, 336

  .align  4
  .global ets_intr_lock
  .type   ets_intr_lock, @function
  .org    0xf74
ets_intr_lock:
  .size   ets_intr_lock, 12

  .align  4
  .global ets_intr_unlock
  .type   ets_intr_unlock, @function
  .org    0xf80
ets_intr_unlock:
  .size   ets_intr_unlock, 8

  .align  4
  .global ets_isr_attach
  .type   ets_isr_attach, @function
  .org    0xf88
ets_isr_attach:
  .size   ets_isr_attach, 16

  .align  4
  .global ets_isr_mask
  .type   ets_isr_mask, @function
  .org    0xf98
ets_isr_mask:
  .size   ets_isr_mask, 16

  .align  4
  .global ets_isr_unmask
  .type   ets_isr_unmask, @function
  .org    0xfa8
ets_isr_unmask:
  .size   ets_isr_unmask, 20

  .align  4
  .global ets_set_user_start
  .type   ets_set_user_start, @function
  .org    0xfbc
ets_set_user_start:
  .size   ets_set_user_start, 48

  .align  4
  .global main
  .type   main, @function
  .org    0xfec
main:
  .size   main, 2232

  .align  4
  .global ets_memset
  .type   ets_memset, @function
  .org    0x18a4
ets_memset:
  .size   ets_memset, 16

  .align  4
  .global ets_memcpy
  .type   ets_memcpy, @function
  .org    0x18b4
ets_memcpy:
  .size   ets_memcpy, 16

  .align  4
  .global ets_memmove
  .type   ets_memmove, @function
  .org    0x18c4
ets_memmove:
  .size   ets_memmove, 16

  .align  4
  .global ets_memcmp
  .type   ets_memcmp, @function
  .org    0x18d4
ets_memcmp:
  .size   ets_memcmp, 196

  .align  4
  .global mem_init
  .type   mem_init, @function
  .org    0x1998
mem_init:
  .size   mem_init, 72

  .align  4
  .global mem_free
  .type   mem_free, @function
  .org    0x19e0
mem_free:
  .size   mem_free, 52

  .align  4
  .global mem_trim
  .type   mem_trim, @function
  .org    0x1a14
mem_trim:
  .size   mem_trim, 300

  .align  4
  .global mem_malloc
  .type   mem_malloc, @function
  .org    0x1b40
mem_malloc:
  .size   mem_malloc, 236

  .align  4
  .global mem_calloc
  .type   mem_calloc, @function
  .org    0x1c2c
mem_calloc:
  .size   mem_calloc, 44

  .align  4
  .global mem_zalloc
  .type   mem_zalloc, @function
  .org    0x1c58
mem_zalloc:
  .size   mem_zalloc, 20

  .align  4
  .global mem_realloc
  .type   mem_realloc, @function
  .org    0x1c6c
mem_realloc:
  .size   mem_realloc, 76

  .align  4
  .global eprintf_init_buf
  .type   eprintf_init_buf, @function
  .org    0x1cb8
eprintf_init_buf:
  .size   eprintf_init_buf, 92

  .align  4
  .global eprintf
  .type   eprintf, @function
  .org    0x1d14
eprintf:
  .size   eprintf, 52

  .align  4
  .global eprintf_to_host
  .type   eprintf_to_host, @function
  .org    0x1d48
eprintf_to_host:
  .size   eprintf_to_host, 88

  .align  4
  .global ets_write_char
  .type   ets_write_char, @function
  .org    0x1da0
ets_write_char:
  .size   ets_write_char, 352

  .align  4
  .global ets_vprintf
  .type   ets_vprintf, @function
  .org    0x1f00
ets_vprintf:
  .size   ets_vprintf, 1324

  .align  4
  .global ets_install_putc1
  .type   ets_install_putc1, @function
  .org    0x242c
ets_install_putc1:
  .size   ets_install_putc1, 12

  .align  4
  .global ets_install_uart_printf
  .type   ets_install_uart_printf, @function
  .org    0x2438
ets_install_uart_printf:
  .size   ets_install_uart_printf, 24

  .align  4
  .global ets_install_external_printf
  .type   ets_install_external_printf, @function
  .org    0x2450
ets_install_external_printf:
  .size   ets_install_external_printf, 60

  .align  4
  .global ets_install_putc2
  .type   ets_install_putc2, @function
  .org    0x248c
ets_install_putc2:
  .size   ets_install_putc2, 8

  .align  4
  .global est_get_printf_buf_remain_len
  .type   est_get_printf_buf_remain_len, @function
  .org    0x2494
est_get_printf_buf_remain_len:
  .size   est_get_printf_buf_remain_len, 8

  .align  4
  .global est_reset_printf_buf_len
  .type   est_reset_printf_buf_len, @function
  .org    0x249c
est_reset_printf_buf_len:
  .size   est_reset_printf_buf_len, 48

  .align  4
  .global ets_printf
  .type   ets_printf, @function
  .org    0x24cc
ets_printf:
  .size   ets_printf, 120

  .align  4
  .global ets_uart_printf
  .type   ets_uart_printf, @function
  .org    0x2544
ets_uart_printf:
  .size   ets_uart_printf, 52

  .align  4
  .global ets_external_printf
  .type   ets_external_printf, @function
  .org    0x2578
ets_external_printf:
  .size   ets_external_printf, 104

  .align  4
  .global rtc_get_reset_reason
  .type   rtc_get_reset_reason, @function
  .org    0x25e0
rtc_get_reset_reason:
  .size   rtc_get_reset_reason, 108

  .align  4
  .global software_reset
  .type   software_reset, @function
  .org    0x264c
software_reset:
  .size   software_reset, 28

  .align  4
  .global rtc_set_sleep_mode
  .type   rtc_set_sleep_mode, @function
  .org    0x2668
rtc_set_sleep_mode:
  .size   rtc_set_sleep_mode, 52

  .align  4
  .global dtm_params_init
  .type   dtm_params_init, @function
  .org    0x269c
dtm_params_init:
  .size   dtm_params_init, 44

  .align  4
  .global dtm_set_intr_mask
  .type   dtm_set_intr_mask, @function
  .org    0x26c8
dtm_set_intr_mask:
  .size   dtm_set_intr_mask, 8

  .align  4
  .global dtm_get_intr_mask
  .type   dtm_get_intr_mask, @function
  .org    0x26d0
dtm_get_intr_mask:
  .size   dtm_get_intr_mask, 12

  .align  4
  .global dtm_set_params
  .type   dtm_set_params, @function
  .org    0x26dc
dtm_set_params:
  .size   dtm_set_params, 200

  .align  4
  .global save_rxbcn_mactime
  .type   save_rxbcn_mactime, @function
  .org    0x27a4
save_rxbcn_mactime:
  .size   save_rxbcn_mactime, 8

  .align  4
  .global save_tsf_us
  .type   save_tsf_us, @function
  .org    0x27ac
save_tsf_us:
  .size   save_tsf_us, 12

  .align  4
  .global ets_enter_sleep
  .type   ets_enter_sleep, @function
  .org    0x27b8
ets_enter_sleep:
  .size   ets_enter_sleep, 184

  .align  4
  .global rtc_enter_sleep
  .type   rtc_enter_sleep, @function
  .org    0x2870
rtc_enter_sleep:
  .size   rtc_enter_sleep, 380

  .align  4
  .global rtc_intr_handler
  .type   rtc_intr_handler, @function
  .org    0x29ec
rtc_intr_handler:
  .size   rtc_intr_handler, 84

  .align  4
  .global ets_rtc_int_register
  .type   ets_rtc_int_register, @function
  .org    0x2a40
ets_rtc_int_register:
  .size   ets_rtc_int_register, 72

  .align  4
  .global ets_strcpy
  .type   ets_strcpy, @function
  .org    0x2a88
ets_strcpy:
  .size   ets_strcpy, 16

  .align  4
  .global ets_strncpy
  .type   ets_strncpy, @function
  .org    0x2a98
ets_strncpy:
  .size   ets_strncpy, 16

  .align  4
  .global ets_strcmp
  .type   ets_strcmp, @function
  .org    0x2aa8
ets_strcmp:
  .size   ets_strcmp, 16

  .align  4
  .global ets_strncmp
  .type   ets_strncmp, @function
  .org    0x2ab8
ets_strncmp:
  .size   ets_strncmp, 16

  .align  4
  .global ets_strlen
  .type   ets_strlen, @function
  .org    0x2ac8
ets_strlen:
  .size   ets_strlen, 16

  .align  4
  .global ets_strstr
  .type   ets_strstr, @function
  .org    0x2ad8
ets_strstr:
  .size   ets_strstr, 16

  .align  4
  .global ets_bzero
  .type   ets_bzero, @function
  .org    0x2ae8
ets_bzero:
  .size   ets_bzero, 16

  .align  4
  .global ets_str2macaddr
  .type   ets_str2macaddr, @function
  .org    0x2af8
ets_str2macaddr:
  .size   ets_str2macaddr, 124

  .align  4
  .global ets_char2xdigit
  .type   ets_char2xdigit, @function
  .org    0x2b74
ets_char2xdigit:
  .size   ets_char2xdigit, 88

  .align  4
  .global ets_getc
  .type   ets_getc, @function
  .org    0x2bcc
ets_getc:
  .size   ets_getc, 28

  .align  4
  .global ets_putc
  .type   ets_putc, @function
  .org    0x2be8
ets_putc:
  .size   ets_putc, 96

  .align  4
  .global ets_timer_setfn
  .type   ets_timer_setfn, @function
  .org    0x2c48
ets_timer_setfn:
  .size   ets_timer_setfn, 28

  .align  4
  .global timer_insert
  .type   timer_insert, @function
  .org    0x2c64
timer_insert:
  .size   timer_insert, 96

  .align  4
  .global ets_timer_arm
  .type   ets_timer_arm, @function
  .org    0x2cc4
ets_timer_arm:
  .size   ets_timer_arm, 124

  .align  4
  .global ets_timer_disarm
  .type   ets_timer_disarm, @function
  .org    0x2d40
ets_timer_disarm:
  .size   ets_timer_disarm, 64

  .align  4
  .global ets_timer_done
  .type   ets_timer_done, @function
  .org    0x2d80
ets_timer_done:
  .size   ets_timer_done, 40

  .align  4
  .global ets_timer_handler_isr
  .type   ets_timer_handler_isr, @function
  .org    0x2da8
ets_timer_handler_isr:
  .size   ets_timer_handler_isr, 192

  .align  4
  .global ets_timer_init
  .type   ets_timer_init, @function
  .org    0x2e68
ets_timer_init:
  .size   ets_timer_init, 100

  .align  4
  .global ets_delay_us
  .type   ets_delay_us, @function
  .org    0x2ecc
ets_delay_us:
  .size   ets_delay_us, 56

  .align  4
  .global ets_update_cpu_frequency
  .type   ets_update_cpu_frequency, @function
  .org    0x2f04
ets_update_cpu_frequency:
  .size   ets_update_cpu_frequency, 8

  .align  4
  .global ets_get_cpu_frequency
  .type   ets_get_cpu_frequency, @function
  .org    0x2f0c
ets_get_cpu_frequency:
  .size   ets_get_cpu_frequency, 40

  .align  4
  .global ets_wdt_get_mode
  .type   ets_wdt_get_mode, @function
  .org    0x2f34
ets_wdt_get_mode:
  .size   ets_wdt_get_mode, 108

  .align  4
  .global ets_wdt_enable
  .type   ets_wdt_enable, @function
  .org    0x2fa0
ets_wdt_enable:
  .size   ets_wdt_enable, 336

  .align  4
  .global ets_wdt_disable
  .type   ets_wdt_disable, @function
  .org    0x30f0
ets_wdt_disable:
  .size   ets_wdt_disable, 104

  .align  4
  .global ets_wdt_restore
  .type   ets_wdt_restore, @function
  .org    0x3158
ets_wdt_restore:
  .size   ets_wdt_restore, 24

  .align  4
  .global ets_wdt_init
  .type   ets_wdt_init, @function
  .org    0x3170
ets_wdt_init:
  .size   ets_wdt_init, 68

  .align  4
  .global roundup2
  .type   roundup2, @function
  .org    0x31b4
roundup2:
  .size   roundup2, 12

  .align  4
  .global multofup
  .type   multofup, @function
  .org    0x31c0
multofup:
  .size   multofup, 112

  .align  4
  .global UartConnCheck
  .type   UartConnCheck, @function
  .org    0x3230
UartConnCheck:
  .size   UartConnCheck, 312

  .align  4
  .global UartDwnLdProc
  .type   UartDwnLdProc, @function
  .org    0x3368
UartDwnLdProc:
  .size   UartDwnLdProc, 464

  .align  4
  .global FlashDwnLdStartMsgProc
  .type   FlashDwnLdStartMsgProc, @function
  .org    0x3538
FlashDwnLdStartMsgProc:
  .size   FlashDwnLdStartMsgProc, 104

  .align  4
  .global FilePacketSendReqMsgProc
  .type   FilePacketSendReqMsgProc, @function
  .org    0x35a0
FilePacketSendReqMsgProc:
  .size   FilePacketSendReqMsgProc, 184

  .align  4
  .global FlashDwnLdStopReqMsgProc
  .type   FlashDwnLdStopReqMsgProc, @function
  .org    0x3658
FlashDwnLdStopReqMsgProc:
  .size   FlashDwnLdStopReqMsgProc, 52

  .align  4
  .global FlashDwnLdParamCfgMsgProc
  .type   FlashDwnLdParamCfgMsgProc, @function
  .org    0x368c
FlashDwnLdParamCfgMsgProc:
  .size   FlashDwnLdParamCfgMsgProc, 56

  .align  4
  .global MemDwnLdStartMsgProc
  .type   MemDwnLdStartMsgProc, @function
  .org    0x36c4
MemDwnLdStartMsgProc:
  .size   MemDwnLdStartMsgProc, 44

  .align  4
  .global MemPacketSendReqMsgProc
  .type   MemPacketSendReqMsgProc, @function
  .org    0x36f0
MemPacketSendReqMsgProc:
  .size   MemPacketSendReqMsgProc, 140

  .align  4
  .global MemDwnLdStopReqMsgProc
  .type   MemDwnLdStopReqMsgProc, @function
  .org    0x377c
MemDwnLdStopReqMsgProc:
  .size   MemDwnLdStopReqMsgProc, 36

  .align  4
  .global UartConnectProc
  .type   UartConnectProc, @function
  .org    0x37a0
UartConnectProc:
  .size   UartConnectProc, 12

  .align  4
  .global UartRegWriteProc
  .type   UartRegWriteProc, @function
  .org    0x37ac
UartRegWriteProc:
  .size   UartRegWriteProc, 112

  .align  4
  .global UartRegReadProc
  .type   UartRegReadProc, @function
  .org    0x381c
UartRegReadProc:
  .size   UartRegReadProc, 32

  .align  4
  .global uartAttach
  .type   uartAttach, @function
  .org    0x383c
uartAttach:
  .size   uartAttach, 104

  .align  4
  .global uart_buff_switch
  .type   uart_buff_switch, @function
  .org    0x38a4
uart_buff_switch:
  .size   uart_buff_switch, 128

  .align  4
  .global uart_baudrate_detect
  .type   uart_baudrate_detect, @function
  .org    0x3924
uart_baudrate_detect:
  .size   uart_baudrate_detect, 180

  .align  4
  .global uart_div_modify
  .type   uart_div_modify, @function
  .org    0x39d8
uart_div_modify:
  .size   uart_div_modify, 60

  .align  4
  .global Uart_Init
  .type   Uart_Init, @function
  .org    0x3a14
Uart_Init:
  .size   Uart_Init, 284

  .align  4
  .global uart_tx_one_char
  .type   uart_tx_one_char, @function
  .org    0x3b30
uart_tx_one_char:
  .size   uart_tx_one_char, 52

  .align  4
  .global uart_rx_one_char_block
  .type   uart_rx_one_char_block, @function
  .org    0x3b64
uart_rx_one_char_block:
  .size   uart_rx_one_char_block, 40

  .align  4
  .global uart_rx_one_char
  .type   uart_rx_one_char, @function
  .org    0x3b8c
uart_rx_one_char:
  .size   uart_rx_one_char, 48

  .align  4
  .global uart_rx_intr_handler
  .type   uart_rx_intr_handler, @function
  .org    0x3bbc
uart_rx_intr_handler:
  .size   uart_rx_intr_handler, 116

  .align  4
  .global UartRxString
  .type   UartRxString, @function
  .org    0x3c30
UartRxString:
  .size   UartRxString, 80

  .align  4
  .global send_packet
  .type   send_packet, @function
  .org    0x3c80
send_packet:
  .size   send_packet, 116

  .align  4
  .global SendMsg
  .type   SendMsg, @function
  .org    0x3cf4
SendMsg:
  .size   SendMsg, 20

  .align  4
  .global recv_packet
  .type   recv_packet, @function
  .org    0x3d08
recv_packet:
  .size   recv_packet, 420

  .align  4
  .global RcvMsg
  .type   RcvMsg, @function
  .org    0x3eac
RcvMsg:
  .size   RcvMsg, 28

  .align  4
  .global uart_rx_readbuff
  .type   uart_rx_readbuff, @function
  .org    0x3ec8
uart_rx_readbuff:
  .size   uart_rx_readbuff, 44

  .align  4
  .global UartGetCmdLn
  .type   UartGetCmdLn, @function
  .org    0x3ef4
UartGetCmdLn:
  .size   UartGetCmdLn, 88

  .align  4
  .global GetUartDevice
  .type   GetUartDevice, @function
  .org    0x3f4c
GetUartDevice:
  .size   GetUartDevice, 12

  .align  4
  .global SelectSpiFunction
  .type   SelectSpiFunction, @function
  .org    0x3f58
SelectSpiFunction:
  .size   SelectSpiFunction, 1136

  .align  4
  .global SPI_read_status
  .type   SPI_read_status, @function
  .org    0x43c8
SPI_read_status:
  .size   SPI_read_status, 56

  .align  4
  .global SPI_write_status
  .type   SPI_write_status, @function
  .org    0x4400
SPI_write_status:
  .size   SPI_write_status, 60

  .align  4
  .global SPI_write_enable
  .type   SPI_write_enable, @function
  .org    0x443c
SPI_write_enable:
  .size   SPI_write_enable, 80

  .align  4
  .global Wait_SPI_Idle
  .type   Wait_SPI_Idle, @function
  .org    0x448c
Wait_SPI_Idle:
  .size   Wait_SPI_Idle, 440

  .align  4
  .global spi_flash_attach
  .type   spi_flash_attach, @function
  .org    0x4644
spi_flash_attach:
  .size   spi_flash_attach, 52

  .align  4
  .global Cache_Read_Enable
  .type   Cache_Read_Enable, @function
  .org    0x4678
Cache_Read_Enable:
  .size   Cache_Read_Enable, 376

  .align  4
  .global Cache_Read_Disable
  .type   Cache_Read_Disable, @function
  .org    0x47f0
Cache_Read_Disable:
  .size   Cache_Read_Disable, 136

  .align  4
  .global SPIUnlock
  .type   SPIUnlock, @function
  .org    0x4878
SPIUnlock:
  .size   SPIUnlock, 48

  .align  4
  .global SPILock
  .type   SPILock, @function
  .org    0x48a8
SPILock:
  .size   SPILock, 68

  .align  4
  .global SPIReadModeCnfig
  .type   SPIReadModeCnfig, @function
  .org    0x48ec
SPIReadModeCnfig:
  .size   SPIReadModeCnfig, 152

  .align  4
  .global SPIEraseChip
  .type   SPIEraseChip, @function
  .org    0x4984
SPIEraseChip:
  .size   SPIEraseChip, 48

  .align  4
  .global SPIEraseBlock
  .type   SPIEraseBlock, @function
  .org    0x49b4
SPIEraseBlock:
  .size   SPIEraseBlock, 76

  .align  4
  .global SPIEraseSector
  .type   SPIEraseSector, @function
  .org    0x4a00
SPIEraseSector:
  .size   SPIEraseSector, 76

  .align  4
  .global SPIWrite
  .type   SPIWrite, @function
  .org    0x4a4c
SPIWrite:
  .size   SPIWrite, 208

  .align  4
  .global SPIRead
  .type   SPIRead, @function
  .org    0x4b1c
SPIRead:
  .size   SPIRead, 40

  .align  4
  .global SPIEraseArea
  .type   SPIEraseArea, @function
  .org    0x4b44
SPIEraseArea:
  .size   SPIEraseArea, 232

  .align  4
  .global SPIParamCfg
  .type   SPIParamCfg, @function
  .org    0x4c2c
SPIParamCfg:
  .size   SPIParamCfg, 36

  .align  4
  .global gpio_init
  .type   gpio_init, @function
  .org    0x4c50
gpio_init:
  .size   gpio_init, 128

  .align  4
  .global gpio_output_set
  .type   gpio_output_set, @function
  .org    0x4cd0
gpio_output_set:
  .size   gpio_output_set, 32

  .align  4
  .global gpio_input_get
  .type   gpio_input_get, @function
  .org    0x4cf0
gpio_input_get:
  .size   gpio_input_get, 20

  .align  4
  .global gpio_register_set
  .type   gpio_register_set, @function
  .org    0x4d04
gpio_register_set:
  .size   gpio_register_set, 88

  .align  4
  .global gpio_register_get
  .type   gpio_register_get, @function
  .org    0x4d5c
gpio_register_get:
  .size   gpio_register_get, 44

  .align  4
  .global gpio_intr_pending
  .type   gpio_intr_pending, @function
  .org    0x4d88
gpio_intr_pending:
  .size   gpio_intr_pending, 8

  .align  4
  .global gpio_pin_intr_state_set
  .type   gpio_pin_intr_state_set, @function
  .org    0x4d90
gpio_pin_intr_state_set:
  .size   gpio_pin_intr_state_set, 60

  .align  4
  .global gpio_intr_ack
  .type   gpio_intr_ack, @function
  .org    0x4dcc
gpio_intr_ack:
  .size   gpio_intr_ack, 92

  .align  4
  .global gpio_intr_handler_register
  .type   gpio_intr_handler_register, @function
  .org    0x4e28
gpio_intr_handler_register:
  .size   gpio_intr_handler_register, 104

  .align  4
  .global gpio_pin_wakeup_enable
  .type   gpio_pin_wakeup_enable, @function
  .org    0x4e90
gpio_pin_wakeup_enable:
  .size   gpio_pin_wakeup_enable, 68

  .align  4
  .global gpio_pin_wakeup_disable
  .type   gpio_pin_wakeup_disable, @function
  .org    0x4ed4
gpio_pin_wakeup_disable:
  .size   gpio_pin_wakeup_disable, 40

  .align  4
  .global gpio_intr_test
  .type   gpio_intr_test, @function
  .org    0x4efc
gpio_intr_test:
  .size   gpio_intr_test, 68

  .align  4
  .global lldesc_build_chain
  .type   lldesc_build_chain, @function
  .org    0x4f40
lldesc_build_chain:
  .size   lldesc_build_chain, 272

  .align  4
  .global lldesc_num2link
  .type   lldesc_num2link, @function
  .org    0x5050
lldesc_num2link:
  .size   lldesc_num2link, 44

  .align  4
  .global lldesc_set_owner
  .type   lldesc_set_owner, @function
  .org    0x507c
lldesc_set_owner:
  .size   lldesc_set_owner, 128

  .align  4
  .global sip_post
  .type   sip_post, @function
  .org    0x50fc
sip_post:
  .size   sip_post, 132

  .align  4
  .global sip_alloc_to_host_evt
  .type   sip_alloc_to_host_evt, @function
  .org    0x5180
sip_alloc_to_host_evt:
  .size   sip_alloc_to_host_evt, 180

  .align  4
  .global sip_to_host_evt_send_done
  .type   sip_to_host_evt_send_done, @function
  .org    0x5234
sip_to_host_evt_send_done:
  .size   sip_to_host_evt_send_done, 140

  .align  4
  .global sip_reclaim_tx_data_pkt
  .type   sip_reclaim_tx_data_pkt, @function
  .org    0x52c0
sip_reclaim_tx_data_pkt:
  .size   sip_reclaim_tx_data_pkt, 140

  .align  4
  .global sip_reclaim_from_host_cmd
  .type   sip_reclaim_from_host_cmd, @function
  .org    0x534c
sip_reclaim_from_host_cmd:
  .size   sip_reclaim_from_host_cmd, 256

  .align  4
  .global sip_install_rx_ctrl_cb
  .type   sip_install_rx_ctrl_cb, @function
  .org    0x544c
sip_install_rx_ctrl_cb:
  .size   sip_install_rx_ctrl_cb, 16

  .align  4
  .global sip_install_rx_data_cb
  .type   sip_install_rx_data_cb, @function
  .org    0x545c
sip_install_rx_data_cb:
  .size   sip_install_rx_data_cb, 524

  .align  4
  .global sip_get_state
  .type   sip_get_state, @function
  .org    0x5668
sip_get_state:
  .size   sip_get_state, 20

  .align  4
  .global sip_init_attach
  .type   sip_init_attach, @function
  .org    0x567c
sip_init_attach:
  .size   sip_init_attach, 72

  .align  4
  .global sip_post_init
  .type   sip_post_init, @function
  .org    0x56c4
sip_post_init:
  .size   sip_post_init, 324

  .align  4
  .global sip_send
  .type   sip_send, @function
  .org    0x5808
sip_send:
  .size   sip_send, 92

  .align  4
  .global sip_to_host_chain_append
  .type   sip_to_host_chain_append, @function
  .org    0x5864
sip_to_host_chain_append:
  .size   sip_to_host_chain_append, 68

  .align  4
  .global sip_get_ptr
  .type   sip_get_ptr, @function
  .org    0x58a8
sip_get_ptr:
  .size   sip_get_ptr, 884

  .align  4
  .global slc_reattach
  .type   slc_reattach, @function
  .org    0x5c1c
slc_reattach:
  .size   slc_reattach, 52

  .align  4
  .global slc_init_attach
  .type   slc_init_attach, @function
  .org    0x5c50
slc_init_attach:
  .size   slc_init_attach, 320

  .align  4
  .global slc_enable
  .type   slc_enable, @function
  .org    0x5d90
slc_enable:
  .size   slc_enable, 40

  .align  4
  .global slc_select_tohost_gpio_mode
  .type   slc_select_tohost_gpio_mode, @function
  .org    0x5db8
slc_select_tohost_gpio_mode:
  .size   slc_select_tohost_gpio_mode, 8

  .align  4
  .global slc_select_tohost_gpio
  .type   slc_select_tohost_gpio, @function
  .org    0x5dc0
slc_select_tohost_gpio:
  .size   slc_select_tohost_gpio, 36

  .align  4
  .global slc_send_to_host_chain
  .type   slc_send_to_host_chain, @function
  .org    0x5de4
slc_send_to_host_chain:
  .size   slc_send_to_host_chain, 176

  .align  4
  .global slc_from_host_chain_recycle
  .type   slc_from_host_chain_recycle, @function
  .org    0x5e94
slc_from_host_chain_recycle:
  .size   slc_from_host_chain_recycle, 124

  .align  4
  .global slc_to_host_chain_recycle
  .type   slc_to_host_chain_recycle, @function
  .org    0x5f10
slc_to_host_chain_recycle:
  .size   slc_to_host_chain_recycle, 20

  .align  4
  .global slc_from_host_chain_fetch
  .type   slc_from_host_chain_fetch, @function
  .org    0x5f24
slc_from_host_chain_fetch:
  .size   slc_from_host_chain_fetch, 240

  .align  4
  .global slc_pause_from_host
  .type   slc_pause_from_host, @function
  .org    0x6014
slc_pause_from_host:
  .size   slc_pause_from_host, 40

  .align  4
  .global slc_resume_from_host
  .type   slc_resume_from_host, @function
  .org    0x603c
slc_resume_from_host:
  .size   slc_resume_from_host, 44

  .align  4
  .global slc_set_host_io_max_window
  .type   slc_set_host_io_max_window, @function
  .org    0x6068
slc_set_host_io_max_window:
  .size   slc_set_host_io_max_window, 36

  .align  4
  .global slc_init_credit
  .type   slc_init_credit, @function
  .org    0x608c
slc_init_credit:
  .size   slc_init_credit, 32

  .align  4
  .global slc_add_credits
  .type   slc_add_credits, @function
  .org    0x60ac
slc_add_credits:
  .size   slc_add_credits, 20

  .align  4
  .global rom_abs_temp
  .type   rom_abs_temp, @function
  .org    0x60c0
rom_abs_temp:
  .size   rom_abs_temp, 16

  .align  4
  .global rom_chip_v5_disable_cca
  .type   rom_chip_v5_disable_cca, @function
  .org    0x60d0
rom_chip_v5_disable_cca:
  .size   rom_chip_v5_disable_cca, 28

  .align  4
  .global rom_chip_v5_enable_cca
  .type   rom_chip_v5_enable_cca, @function
  .org    0x60ec
rom_chip_v5_enable_cca:
  .size   rom_chip_v5_enable_cca, 32

  .align  4
  .global rom_chip_v5_sense_backoff
  .type   rom_chip_v5_sense_backoff, @function
  .org    0x610c
rom_chip_v5_sense_backoff:
  .size   rom_chip_v5_sense_backoff, 80

  .align  4
  .global rom_dc_iq_est
  .type   rom_dc_iq_est, @function
  .org    0x615c
rom_dc_iq_est:
  .size   rom_dc_iq_est, 92

  .align  4
  .global rom_en_pwdet
  .type   rom_en_pwdet, @function
  .org    0x61b8
rom_en_pwdet:
  .size   rom_en_pwdet, 128

  .align  4
  .global rom_get_bb_atten
  .type   rom_get_bb_atten, @function
  .org    0x6238
rom_get_bb_atten:
  .size   rom_get_bb_atten, 40

  .align  4
  .global rom_get_corr_power
  .type   rom_get_corr_power, @function
  .org    0x6260
rom_get_corr_power:
  .size   rom_get_corr_power, 124

  .align  4
  .global rom_get_fm_sar_dout
  .type   rom_get_fm_sar_dout, @function
  .org    0x62dc
rom_get_fm_sar_dout:
  .size   rom_get_fm_sar_dout, 184

  .align  4
  .global rom_get_noisefloor
  .type   rom_get_noisefloor, @function
  .org    0x6394
rom_get_noisefloor:
  .size   rom_get_noisefloor, 28

  .align  4
  .global rom_get_power_db
  .type   rom_get_power_db, @function
  .org    0x63b0
rom_get_power_db:
  .size   rom_get_power_db, 80

  .align  4
  .global rom_iq_est_disable
  .type   rom_iq_est_disable, @function
  .org    0x6400
rom_iq_est_disable:
  .size   rom_iq_est_disable, 48

  .align  4
  .global rom_iq_est_enable
  .type   rom_iq_est_enable, @function
  .org    0x6430
rom_iq_est_enable:
  .size   rom_iq_est_enable, 84

  .align  4
  .global rom_linear_to_db
  .type   rom_linear_to_db, @function
  .org    0x6484
rom_linear_to_db:
  .size   rom_linear_to_db, 136

  .align  4
  .global rom_set_txclk_en
  .type   rom_set_txclk_en, @function
  .org    0x650c
rom_set_txclk_en:
  .size   rom_set_txclk_en, 68

  .align  4
  .global rom_set_rxclk_en
  .type   rom_set_rxclk_en, @function
  .org    0x6550
rom_set_rxclk_en:
  .size   rom_set_rxclk_en, 84

  .align  4
  .global rom_mhz2ieee
  .type   rom_mhz2ieee, @function
  .org    0x65a4
rom_mhz2ieee:
  .size   rom_mhz2ieee, 132

  .align  4
  .global rom_rxiq_get_mis
  .type   rom_rxiq_get_mis, @function
  .org    0x6628
rom_rxiq_get_mis:
  .size   rom_rxiq_get_mis, 272

  .align  4
  .global rom_sar_init
  .type   rom_sar_init, @function
  .org    0x6738
rom_sar_init:
  .size   rom_sar_init, 84

  .align  4
  .global rom_set_ana_inf_tx_scale
  .type   rom_set_ana_inf_tx_scale, @function
  .org    0x678c
rom_set_ana_inf_tx_scale:
  .size   rom_set_ana_inf_tx_scale, 60

  .align  4
  .global rom_set_loopback_gain
  .type   rom_set_loopback_gain, @function
  .org    0x67c8
rom_set_loopback_gain:
  .size   rom_set_loopback_gain, 104

  .align  4
  .global rom_set_noise_floor
  .type   rom_set_noise_floor, @function
  .org    0x6830
rom_set_noise_floor:
  .size   rom_set_noise_floor, 68

  .align  4
  .global rom_start_noisefloor
  .type   rom_start_noisefloor, @function
  .org    0x6874
rom_start_noisefloor:
  .size   rom_start_noisefloor, 64

  .align  4
  .global rom_start_tx_tone
  .type   rom_start_tx_tone, @function
  .org    0x68b4
rom_start_tx_tone:
  .size   rom_start_tx_tone, 216

  .align  4
  .global rom_stop_tx_tone
  .type   rom_stop_tx_tone, @function
  .org    0x698c
rom_stop_tx_tone:
  .size   rom_stop_tx_tone, 144

  .align  4
  .global rom_txtone_linear_pwr
  .type   rom_txtone_linear_pwr, @function
  .org    0x6a1c
rom_txtone_linear_pwr:
  .size   rom_txtone_linear_pwr, 124

  .align  4
  .global rom_tx_mac_disable
  .type   rom_tx_mac_disable, @function
  .org    0x6a98
rom_tx_mac_disable:
  .size   rom_tx_mac_disable, 60

  .align  4
  .global rom_tx_mac_enable
  .type   rom_tx_mac_enable, @function
  .org    0x6ad4
rom_tx_mac_enable:
  .size   rom_tx_mac_enable, 52

  .align  4
  .global phy_get_romfuncs
  .type   phy_get_romfuncs, @function
  .org    0x6b08
phy_get_romfuncs:
  .size   phy_get_romfuncs, 8

  .align  4
  .global rom_ana_inf_gating_en
  .type   rom_ana_inf_gating_en, @function
  .org    0x6b10
rom_ana_inf_gating_en:
  .size   rom_ana_inf_gating_en, 320

  .align  4
  .global rom_set_channel_freq
  .type   rom_set_channel_freq, @function
  .org    0x6c50
rom_set_channel_freq:
  .size   rom_set_channel_freq, 820

  .align  4
  .global rom_chip_50_set_channel
  .type   rom_chip_50_set_channel, @function
  .org    0x6f84
rom_chip_50_set_channel:
  .size   rom_chip_50_set_channel, 408

  .align  4
  .global rom_chip_v5_rx_init
  .type   rom_chip_v5_rx_init, @function
  .org    0x711c
rom_chip_v5_rx_init:
  .size   rom_chip_v5_rx_init, 112

  .align  4
  .global rom_chip_v5_tx_init
  .type   rom_chip_v5_tx_init, @function
  .org    0x718c
rom_chip_v5_tx_init:
  .size   rom_chip_v5_tx_init, 220

  .align  4
  .global rom_i2c_readReg
  .type   rom_i2c_readReg, @function
  .org    0x7268
rom_i2c_readReg:
  .size   rom_i2c_readReg, 52

  .align  4
  .global rom_i2c_readReg_Mask
  .type   rom_i2c_readReg_Mask, @function
  .org    0x729c
rom_i2c_readReg_Mask:
  .size   rom_i2c_readReg_Mask, 60

  .align  4
  .global rom_i2c_writeReg
  .type   rom_i2c_writeReg, @function
  .org    0x72d8
rom_i2c_writeReg:
  .size   rom_i2c_writeReg, 52

  .align  4
  .global rom_i2c_writeReg_Mask
  .type   rom_i2c_writeReg_Mask, @function
  .org    0x730c
rom_i2c_writeReg_Mask:
  .size   rom_i2c_writeReg_Mask, 112

  .align  4
  .global rom_pbus_debugmode
  .type   rom_pbus_debugmode, @function
  .org    0x737c
rom_pbus_debugmode:
  .size   rom_pbus_debugmode, 148

  .align  4
  .global rom_pbus_enter_debugmode
  .type   rom_pbus_enter_debugmode, @function
  .org    0x7410
rom_pbus_enter_debugmode:
  .size   rom_pbus_enter_debugmode, 56

  .align  4
  .global rom_pbus_exit_debugmode
  .type   rom_pbus_exit_debugmode, @function
  .org    0x7448
rom_pbus_exit_debugmode:
  .size   rom_pbus_exit_debugmode, 52

  .align  4
  .global rom_pbus_force_test
  .type   rom_pbus_force_test, @function
  .org    0x747c
rom_pbus_force_test:
  .size   rom_pbus_force_test, 92

  .align  4
  .global rom_pbus_rd
  .type   rom_pbus_rd, @function
  .org    0x74d8
rom_pbus_rd:
  .size   rom_pbus_rd, 116

  .align  4
  .global rom_pbus_set_rxgain
  .type   rom_pbus_set_rxgain, @function
  .org    0x754c
rom_pbus_set_rxgain:
  .size   rom_pbus_set_rxgain, 196

  .align  4
  .global rom_pbus_set_txgain
  .type   rom_pbus_set_txgain, @function
  .org    0x7610
rom_pbus_set_txgain:
  .size   rom_pbus_set_txgain, 56

  .align  4
  .global rom_pbus_workmode
  .type   rom_pbus_workmode, @function
  .org    0x7648
rom_pbus_workmode:
  .size   rom_pbus_workmode, 64

  .align  4
  .global rom_pbus_xpd_rx_off
  .type   rom_pbus_xpd_rx_off, @function
  .org    0x7688
rom_pbus_xpd_rx_off:
  .size   rom_pbus_xpd_rx_off, 68

  .align  4
  .global rom_pbus_xpd_rx_on
  .type   rom_pbus_xpd_rx_on, @function
  .org    0x76cc
rom_pbus_xpd_rx_on:
  .size   rom_pbus_xpd_rx_on, 48

  .align  4
  .global rom_pbus_xpd_tx_off
  .type   rom_pbus_xpd_tx_off, @function
  .org    0x76fc
rom_pbus_xpd_tx_off:
  .size   rom_pbus_xpd_tx_off, 68

  .align  4
  .global rom_pbus_xpd_tx_on
  .type   rom_pbus_xpd_tx_on, @function
  .org    0x7740
rom_pbus_xpd_tx_on:
  .size   rom_pbus_xpd_tx_on, 96

  .align  4
  .global rom_pbus_xpd_tx_on__low_gain
  .type   rom_pbus_xpd_tx_on__low_gain, @function
  .org    0x77a0
rom_pbus_xpd_tx_on__low_gain:
  .size   rom_pbus_xpd_tx_on__low_gain, 100

  .align  4
  .global rom_phy_reset_req
  .type   rom_phy_reset_req, @function
  .org    0x7804
rom_phy_reset_req:
  .size   rom_phy_reset_req, 24

  .align  4
  .global rom_restart_cal
  .type   rom_restart_cal, @function
  .org    0x781c
rom_restart_cal:
  .size   rom_restart_cal, 76

  .align  4
  .global rom_rfpll_reset
  .type   rom_rfpll_reset, @function
  .org    0x7868
rom_rfpll_reset:
  .size   rom_rfpll_reset, 116

  .align  4
  .global rom_write_rfpll_sdm
  .type   rom_write_rfpll_sdm, @function
  .org    0x78dc
rom_write_rfpll_sdm:
  .size   rom_write_rfpll_sdm, 140

  .align  4
  .global rom_rfpll_set_freq
  .type   rom_rfpll_set_freq, @function
  .org    0x7968
rom_rfpll_set_freq:
  .size   rom_rfpll_set_freq, 192

  .align  4
  .global rom_cal_tos_v50
  .type   rom_cal_tos_v50, @function
  .org    0x7a28
rom_cal_tos_v50:
  .size   rom_cal_tos_v50, 456

  .align  4
  .global rom_pbus_dco___SA2
  .type   rom_pbus_dco___SA2, @function
  .org    0x7bf0
rom_pbus_dco___SA2:
  .size   rom_pbus_dco___SA2, 708

  .align  4
  .global rom_rfcal_pwrctrl
  .type   rom_rfcal_pwrctrl, @function
  .org    0x7eb4
rom_rfcal_pwrctrl:
  .size   rom_rfcal_pwrctrl, 408

  .align  4
  .global rom_rfcal_rxiq
  .type   rom_rfcal_rxiq, @function
  .org    0x804c
rom_rfcal_rxiq:
  .size   rom_rfcal_rxiq, 536

  .align  4
  .global rom_rfcal_rxiq_set_reg
  .type   rom_rfcal_rxiq_set_reg, @function
  .org    0x8264
rom_rfcal_rxiq_set_reg:
  .size   rom_rfcal_rxiq_set_reg, 292

  .align  4
  .global rom_rfcal_txcap
  .type   rom_rfcal_txcap, @function
  .org    0x8388
rom_rfcal_txcap:
  .size   rom_rfcal_txcap, 648

  .align  4
  .global rom_rfcal_txiq
  .type   rom_rfcal_txiq, @function
  .org    0x8610
rom_rfcal_txiq:
  .size   rom_rfcal_txiq, 680

  .align  4
  .global rom_rfcal_txiq_cover
  .type   rom_rfcal_txiq_cover, @function
  .org    0x88b8
rom_rfcal_txiq_cover:
  .size   rom_rfcal_txiq_cover, 440

  .align  4
  .global rom_rfcal_txiq_set_reg
  .type   rom_rfcal_txiq_set_reg, @function
  .org    0x8a70
rom_rfcal_txiq_set_reg:
  .size   rom_rfcal_txiq_set_reg, 252

  .align  4
  .global rom_rxiq_cover_mg_mp
  .type   rom_rxiq_cover_mg_mp, @function
  .org    0x8b6c
rom_rxiq_cover_mg_mp:
  .size   rom_rxiq_cover_mg_mp, 256

  .align  4
  .global rom_set_txbb_atten
  .type   rom_set_txbb_atten, @function
  .org    0x8c6c
rom_set_txbb_atten:
  .size   rom_set_txbb_atten, 200

  .align  4
  .global rom_set_txiq_cal
  .type   rom_set_txiq_cal, @function
  .org    0x8d34
rom_set_txiq_cal:
  .size   rom_set_txiq_cal, 156

  .align  4
  .global rijndaelKeySetupDec
  .type   rijndaelKeySetupDec, @function
  .org    0x8dd0
rijndaelKeySetupDec:
  .size   rijndaelKeySetupDec, 212

  .align  4
  .global aes_decrypt_init
  .type   aes_decrypt_init, @function
  .org    0x8ea4
aes_decrypt_init:
  .size   aes_decrypt_init, 1072

  .align  4
  .global aes_decrypt
  .type   aes_decrypt, @function
  .org    0x92d4
aes_decrypt:
  .size   aes_decrypt, 16

  .align  4
  .global aes_decrypt_deinit
  .type   aes_decrypt_deinit, @function
  .org    0x92e4
aes_decrypt_deinit:
  .size   aes_decrypt_deinit, 28

  .align  4
  .global rijndaelKeySetupEnc
  .type   rijndaelKeySetupEnc, @function
  .org    0x9300
rijndaelKeySetupEnc:
  .size   rijndaelKeySetupEnc, 272

  .align  4
  .global aes_unwrap
  .type   aes_unwrap, @function
  .org    0x9410
aes_unwrap:
  .size   aes_unwrap, 236

  .align  4
  .global base64_encode
  .type   base64_encode, @function
  .org    0x94fc
base64_encode:
  .size   base64_encode, 332

  .align  4
  .global base64_decode
  .type   base64_decode, @function
  .org    0x9648
base64_decode:
  .size   base64_decode, 356

  .align  4
  .global md5_vector
  .type   md5_vector, @function
  .org    0x97ac
md5_vector:
  .size   md5_vector, 108

  .align  4
  .global MD5Init
  .type   MD5Init, @function
  .org    0x9818
MD5Init:
  .size   MD5Init, 28

  .align  4
  .global MD5Update
  .type   MD5Update, @function
  .org    0x9834
MD5Update:
  .size   MD5Update, 204

  .align  4
  .global MD5Final
  .type   MD5Final, @function
  .org    0x9900
MD5Final:
  .size   MD5Final, 2144

  .align  4
  .global hmac_md5_vector
  .type   hmac_md5_vector, @function
  .org    0xa160
hmac_md5_vector:
  .size   hmac_md5_vector, 364

  .align  4
  .global hmac_md5
  .type   hmac_md5, @function
  .org    0xa2cc
hmac_md5:
  .size   hmac_md5, 32

  .align  4
  .global sha1_vector
  .type   sha1_vector, @function
  .org    0xa2ec
sha1_vector:
  .size   sha1_vector, 120

  .align  4
  .global SHA1Transform
  .type   SHA1Transform, @function
  .org    0xa364
SHA1Transform:
  .size   SHA1Transform, 4640

  .align  4
  .global SHA1Init
  .type   SHA1Init, @function
  .org    0xb584
SHA1Init:
  .size   SHA1Init, 36

  .align  4
  .global SHA1Update
  .type   SHA1Update, @function
  .org    0xb5a8
SHA1Update:
  .size   SHA1Update, 160

  .align  4
  .global SHA1Final
  .type   SHA1Final, @function
  .org    0xb648
SHA1Final:
  .size   SHA1Final, 504

  .align  4
  .global pbkdf2_sha1
  .type   pbkdf2_sha1, @function
  .org    0xb840
pbkdf2_sha1:
  .size   pbkdf2_sha1, 116

  .align  4
  .global hmac_sha1_vector
  .type   hmac_sha1_vector, @function
  .org    0xb8b4
hmac_sha1_vector:
  .size   hmac_sha1_vector, 372

  .align  4
  .global hmac_sha1
  .type   hmac_sha1, @function
  .org    0xba28
hmac_sha1:
  .size   hmac_sha1, 32

  .align  4
  .global sha1_prf
  .type   sha1_prf, @function
  .org    0xba48
sha1_prf:
  .size   sha1_prf, 244

  .align  4
  .global wepkey_64
  .type   wepkey_64, @function
  .org    0xbb3c
wepkey_64:
  .size   wepkey_64, 260

  .align  4
  .global wepkey_128
  .type   wepkey_128, @function
  .org    0xbc40
wepkey_128:
  .size   wepkey_128, 232

  .align  4
  .global _xtos_set_interrupt_handler_arg
  .type   _xtos_set_interrupt_handler_arg, @function
  .org    0xbd28
_xtos_set_interrupt_handler_arg:
  .size   _xtos_set_interrupt_handler_arg, 72

  .align  4
  .global _xtos_set_interrupt_handler
  .type   _xtos_set_interrupt_handler, @function
  .org    0xbd70
_xtos_set_interrupt_handler:
  .size   _xtos_set_interrupt_handler, 20

  .align  4
  .global _xtos_ints_on
  .type   _xtos_ints_on, @function
  .org    0xbd84
_xtos_ints_on:
  .size   _xtos_ints_on, 32

  .align  4
  .global _xtos_ints_off
  .type   _xtos_ints_off, @function
  .org    0xbda4
_xtos_ints_off:
  .size   _xtos_ints_off, 36

  .align  4
  .global strcmp
  .type   strcmp, @function
  .org    0xbdc8
strcmp:
  .size   strcmp, 256

  .align  4
  .global strcpy
  .type   strcpy, @function
  .org    0xbec8
strcpy:
  .size   strcpy, 132

  .align  4
  .global strlen
  .type   strlen, @function
  .org    0xbf4c
strlen:
  .size   strlen, 92

  .align  4
  .global strncmp
  .type   strncmp, @function
  .org    0xbfa8
strncmp:
  .size   strncmp, 248

  .align  4
  .global strncpy
  .type   strncpy, @function
  .org    0xc0a0
strncpy:
  .size   strncpy, 224

  .align  4
  .global __addsf3
  .type   __addsf3, @function
  .org    0xc180
__addsf3:
  .size   __addsf3, 232

  .align  4
  .global __subsf3
  .type   __subsf3, @function
  .org    0xc268
__subsf3:
  .size   __subsf3, 372

  .align  4
  .global __mulsf3
  .type   __mulsf3, @function
  .org    0xc3dc
__mulsf3:
  .size   __mulsf3, 232

  .align  4
  .global __fixunssfsi
  .type   __fixunssfsi, @function
  .org    0xc4c4
__fixunssfsi:
  .size   __fixunssfsi, 116

  .align  4
  .global __adddf3
  .type   __adddf3, @function
  .org    0xc538
__adddf3:
  .size   __adddf3, 336

  .align  4
  .global __subdf3
  .type   __subdf3, @function
  .org    0xc688
__subdf3:
  .size   __subdf3, 616

  .align  4
  .global __muldf3
  .type   __muldf3, @function
  .org    0xc8f0
__muldf3:
  .size   __muldf3, 676

  .align  4
  .global __divdf3
  .type   __divdf3, @function
  .org    0xcb94
__divdf3:
  .size   __divdf3, 292

  .align  4
  .global __fixdfsi
  .type   __fixdfsi, @function
  .org    0xccb8
__fixdfsi:
  .size   __fixdfsi, 72

  .align  4
  .global __fixunsdfsi
  .type   __fixunsdfsi, @function
  .org    0xcd00
__fixunsdfsi:
  .size   __fixunsdfsi, 92

  .align  4
  .global __truncdfsf2
  .type   __truncdfsf2, @function
  .org    0xcd5c
__truncdfsf2:
  .size   __truncdfsf2, 160

  .align  4
  .global __extendsfdf2
  .type   __extendsfdf2, @function
  .org    0xcdfc
__extendsfdf2:
  .size   __extendsfdf2, 100

  .align  4
  .global __divdi3
  .type   __divdi3, @function
  .org    0xce60
__divdi3:
  .size   __divdi3, 1200

  .align  4
  .global __udivdi3
  .type   __udivdi3, @function
  .org    0xd310
__udivdi3:
  .size   __udivdi3, 1120

  .align  4
  .global __umoddi3
  .type   __umoddi3, @function
  .org    0xd770
__umoddi3:
  .size   __umoddi3, 1136

  .align  4
  .global _xtos_alloca_handler
  .type   _xtos_alloca_handler, @function
  .org    0xdbe0
_xtos_alloca_handler:
  .size   _xtos_alloca_handler, 4

  .align  4
  .global _xtos_syscall_handler
  .type   _xtos_syscall_handler, @function
  .org    0xdbe4
_xtos_syscall_handler:
  .size   _xtos_syscall_handler, 20

  .align  4
  .global _xtos_p_none
  .type   _xtos_p_none, @function
  .org    0xdbf8
_xtos_p_none:
  .size   _xtos_p_none, 4

  .align  4
  .global _xtos_set_intlevel
  .type   _xtos_set_intlevel, @function
  .org    0xdbfc
_xtos_set_intlevel:
  .size   _xtos_set_intlevel, 28

  .align  4
  .global _xtos_set_min_intlevel
  .type   _xtos_set_min_intlevel, @function
  .org    0xdc18
_xtos_set_min_intlevel:
  .size   _xtos_set_min_intlevel, 36

  .align  4
  .global _xtos_unhandled_interrupt
  .type   _xtos_unhandled_interrupt, @function
  .org    0xdc3c
_xtos_unhandled_interrupt:
  .size   _xtos_unhandled_interrupt, 8

  .align  4
  .global _xtos_unhandled_exception
  .type   _xtos_unhandled_exception, @function
  .org    0xdc44
_xtos_unhandled_exception:
  .size   _xtos_unhandled_exception, 16

  .align  4
  .global _xtos_return_from_exc
  .type   _xtos_return_from_exc, @function
  .org    0xdc54
_xtos_return_from_exc:
  .size   _xtos_return_from_exc, 52

  .align  4
  .global __divsi3
  .type   __divsi3, @function
  .org    0xdc88
__divsi3:
  .size   __divsi3, 104

  .align  4
  .global __umulsidi3
  .type   __umulsidi3, @function
  .org    0xdcf0
__umulsidi3:
  .size   __umulsidi3, 72

  .align  4
  .global xthal_get_ccount
  .type   xthal_get_ccount, @function
  .org    0xdd38
xthal_get_ccount:
  .size   xthal_get_ccount, 8

  .align  4
  .global xthal_set_ccompare
  .type   xthal_set_ccompare, @function
  .org    0xdd40
xthal_set_ccompare:
  .size   xthal_set_ccompare, 12

  .align  4
  .global xthal_get_ccompare
  .type   xthal_get_ccompare, @function
  .org    0xdd4c
xthal_get_ccompare:
  .size   xthal_get_ccompare, 12

  .align  4
  .global xthal_get_interrupt
  .type   xthal_get_interrupt, @function
  .org    0xdd58
xthal_get_interrupt:
  .size   xthal_get_interrupt, 0

  .align  4
  .global xthal_get_intread
  .type   xthal_get_intread, @function
  .org    0xdd58
xthal_get_intread:
  .size   xthal_get_intread, 8

  .align  4
  .global xthal_set_intclear
  .type   xthal_set_intclear, @function
  .org    0xdd60
xthal_set_intclear:
  .size   xthal_set_intclear, 8

  .align  4
  .global rc4_skip
  .type   rc4_skip, @function
  .org    0xdd68
rc4_skip:
  .size   rc4_skip, 284

  .align  4
  .global bzero
  .type   bzero, @function
  .org    0xde84
bzero:
  .size   bzero, 36

  .align  4
  .global memcmp
  .type   memcmp, @function
  .org    0xdea8
memcmp:
  .size   memcmp, 160

  .align  4
  .global memcpy
  .type   memcpy, @function
  .org    0xdf48
memcpy:
  .size   memcpy, 260

  .align  4
  .global memmove
  .type   memmove, @function
  .org    0xe04c
memmove:
  .size   memmove, 324

  .align  4
  .global memset
  .type   memset, @function
  .org    0xe190
memset:
  .size   memset, 80

  .align  4
  .global strstr
  .type   strstr, @function
  .org    0xe1e0
strstr:
  .size   strstr, 60

  .align  4
  .global __udivsi3
  .type   __udivsi3, @function
  .org    0xe21c
__udivsi3:
  .size   __udivsi3, 76

  .align  4
  .global __umodsi3
  .type   __umodsi3, @function
  .org    0xe268
__umodsi3:
  .size   __umodsi3, 60

  .align  4
  .global __floatunsisf
  .type   __floatunsisf, @function
  .org    0xe2a4
__floatunsisf:
  .size   __floatunsisf, 8

  .align  4
  .global __floatsisf
  .type   __floatsisf, @function
  .org    0xe2ac
__floatsisf:
  .size   __floatsisf, 60

  .align  4
  .global __floatunsidf
  .type   __floatunsidf, @function
  .org    0xe2e8
__floatunsidf:
  .size   __floatunsidf, 8

  .align  4
  .global __floatsidf
  .type   __floatsidf, @function
  .org    0xe2f0
__floatsidf:
  .size   __floatsidf, 48

  .align  4
  .global xthal_spill_registers_into_stack_nw
  .type   xthal_spill_registers_into_stack_nw, @function
  .org    0xe320
xthal_spill_registers_into_stack_nw:
  .size   xthal_spill_registers_into_stack_nw, 0

  .align  4
  .global xthal_window_spill_nw
  .type   xthal_window_spill_nw, @function
  .org    0xe320
xthal_window_spill_nw:
  .size   xthal_window_spill_nw, 4

  .align  4
  .global xthal_window_spill
  .type   xthal_window_spill, @function
  .org    0xe324
xthal_window_spill:
  .size   xthal_window_spill, 4

  .align  4
  .global _rom_store_table
  .type   _rom_store_table, @function
  .org    0xe328
_rom_store_table:
  .size   _rom_store_table, 96

