let GATT = {
  PROP_READ: 1,
  PROP_WRITE: 2,
  PROP_NOTIFY: 4,
  PROP_INDICATE: 8,

  SEC_LEVEL_NONE: 0,
  SEC_LEVEL_AUTH: 1,
  SEC_LEVEL_ENCR: 2,
  SEC_LEVEL_ENCR_MITM: 3,

  NOTIFY_MODE_OFF: 0,
  NOTIFY_MODE_NOTIFY: 1,
  NOTIFY_MODE_INDICATE: 2,

  STATUS_OK: 0,
  STATUS_INVALID_HANDLE: -1,
  STATUS_READ_NOT_PERMITTED: -2,
  STATUS_WRITE_NOT_PERMITTED: -3,
  STATUS_INSUF_AUTHENTICATION: -4,
  STATUS_REQUEST_NOT_SUPPORTED: -5,
  STATUS_INVALID_OFFSET: -6,
  STATUS_INSUF_AUTHORIZATION: -7,
  STATUS_INVALID_ATT_VAL_LENGTH: -8,
  STATUS_UNLIKELY_ERROR: -9,
  STATUS_INSUF_RESOURCES: -10,

  // ## **`GATT.RWNI(r, w, n, i)`**
  // Helper for combining common char property bits.
  PROP_RWNI: function (r, w, n, i) {
    return (r ? GATT.PROP_READ : 0) |
           (w ? GATT.PROP_WRITE : 0) |
           (n ? GATT.PROP_NOTIFY : 0) |
           (i ? GATT.PROP_INDICATE : 0);
  },
};
