APP = hello
APP_MODULES = src
APP_FS_PATH = $(CURDIR)/fs
APP_CONF_SCHEMA = $(CURDIR)/src/conf_schema.yaml
MG_ENABLE_JS = 0
MG_ENABLE_CLUBBY = 0

include $(MIOT_PATH)/fw/platforms/$(PLATFORM)/Makefile.build
