
== Building Smart.js firmware

For those who want to build Smart.js firmware themselves, here is an
instruction on how to do that:

1. Make sure you have link:https://www.docker.com/[Docker] installed and running
2. Execute the following:

```
$ git clone https://github.com/cesanta/smart.js.git
$ cd smart.js/platforms/esp8266
$ make
```

The firmware gets built in the `firmware/` folder. Copy it to the
Fish'n'chips's `firmware/esp8266/` directory, and it'll be ready to flash!

NOTE: for Windows users:
- Operations above should be performed from `boot2docker` console, not from `cmd.exe`
- Only `C:\Users` is mapped into docker's VM by default, so put cloned repo to `Users` subfolder

NOTE: for Mac users:
- Only `/Users` is mapped into docker's VM by default, so put cloned repo to `Users` subfolder

=== Extending Smart.js firmware

It is trivial to add more API functions to the Smart.js firmware.
Smart.js is built on top of
link:https://github.com/cesanta/v7/[V7 JavaScript engine] which makes it easy
to export C/C++ functions to JavaScript:

- link:https://docs.cesanta.com/v7/#_call_c_c_function_from_javascript[V7 reference on exporting C/C++ functions to JS]
- See `init_v7()` function at link:https://github.com/cesanta/smart.js/blob/master/platforms/esp8266/user/v7_esp.c[v7_esp.c] for an example of how specific C/C++ API is exported to ESP8266 firmware. To extend it, just edit `init_v7()` function and rebuild the firmare by running `make` in `smartjs/platforms/esp8266` directory.
