
== JavaScript API reference

=== String

Smart.js has several non-standard extensions for `String.prototype` in
order to give a compact and fast API to access raw data obtained from
File, Socket, and hardware input/output such as I2C.
Smart.js IO API functions return
string data as a result of read operations, and that string data is a
raw byte array. ECMA6 provides `ArrayBuffer` and `DataView` API for dealing
with raw bytes, because strings in JavaScript are Unicode. That standard
API is too bloated for the embedded use, and does not allow to use handy
String API (e.g. `.match()`) against data.

Smart.js internally stores strings as byte arrays. All strings created by the
String API are UTF8 encoded. Strings that are the result of
input/output API calls might not be a valid UTF8 strings, but nevertheless
they are represented as strings, and the following API allows to access
underlying byte sequence:

`String.prototype.at(position) -> number or NaN`::
  Return byte at index
  `position`. Byte value is in 0,255 range. If `position` is out of bounds
  (either negative or larger then the byte array length), NaN is returned.
  Example: `"ы".at(0)` returns 0xd1.
`String.prototype.blen -> number`::
  Return string length in bytes.
  Example: `"ы".blen` returns 2. Note that `"ы".length` is 1, since that
  string consists of a single Unicode character (2-byte).

=== File

File API is a wrapper around standard C calls `fopen()`, `fclose()`,
`fread()`, `fwrite()`, `rename()`, `remove()`.

`File.open(file_name [, mode]) -> file_object or null`::
  Open a file `path`. For
  list of valid `mode` values, see `fopen()` documentation. If `mode` is
  not specified, mode `rb` is used, i.e. file is opened in read-only mode.
  Return an opened file object, or null on error. Example:
  `var f = File.open('/etc/passwd'); f.close();`
`file_obj.close() -> undefined`::
  Close opened file object.
  NOTE: it is user's responsibility to close all opened file streams. V7
  does not do that automatically.
`file_obj.read() -> string`::
  Read portion of data from
  an opened file stream. Return string with data, or empty string on EOF
  or error.
`file_obj.readAll() -> string`::
  Same as `read()`, but keeps reading data until EOF.
`file_obj.write(str) -> num_bytes_written`::
  Write string `str` to the opened file object. Return number of bytes written.
`File.rename(old_name, new_name) -> errno`::
  Rename file `old_name` to
  `new_name`. Return 0 on success, or `errno` value on error.
`File.remove(file_name) -> errno`::
  Delete file `file_name`.
  Return 0 on success, or `errno` value on error.
`File.list(dir_name) -> array_of_names`::
  Return a list of files in a given directory, or `undefined` on error.

NOTE: some file systems, e.g. SPIFFS on ESP8266 platform, are flat. They
do not support directory structure. Instead, all files reside in the
top-level directory.

=== HTTP

Smart.js implements a subset of node.js HTTP API. This snippet demonstrates
what is supported for client and server:

```
    var server = Http.createServer(function(req, res) {
      if (req.url == '/hello') {
        res.writeHead(200, {'Content-Type': 'text/plain'});
        res.write(req);
        res.end('\n');
      } else {
        res.serve({ document_root: '/tmp' });
      }
    }).listen('127.0.0.1:8000');

    var client = Http.request({
      hostname: '127.0.0.1',
      port: 8000,
      path: '/hello',
      method: 'POST',
      headers: { MyHeader: 'hi there' }
    }, function(res) {
      print('in reply handler', res);
    }).end('this is POST data');
```


`Http.createServer(function(req, res) {}) -> server_obj`::
  Create HTTP server instance
`server_obj.listen(address) -> server_obj`::
  Start listening on given address. Address could be a port number,
  or a `IP_ADDRESS:PORT_NUMBER` string.
`response_obj.writeHead(code, headers) -> null`::
  Write response status line and HTTP headers
`response_obj.write(data) -> null`::
  Write HTTP body data. Could be called multiple times.
`response_obj.end(optional_data) -> null`::
  Finish sending HTTP body


`Http.request(options_obj, callback) -> client_obj`::
  Create HTTP client
`client_obj.end(optional_post_data) -> client_obj`::
  Finish sending HTTP body

=== WebSocket

Smart.js's provides WebSocket client functionality. The API follows the
standard - the same way it works in any browser.  Please refer to the
link:https://developer.mozilla.org/en-US/docs/Web/API/WebSocket[API Reference]
for the detailed reference. Below is a usage example:

```
var ws = new WebSocket('ws://echo.websocket.org');

ws.onopen = function(ev) {
  ws.send('hi');
};

ws.onmessage = function(ev) {
  print('Received WS data: ', ev.data);
  ws.close();
};

```

=== MQTT

Smart.js provides a simple MQTT client. The API is modeled after
the popular JS MQTT client https://www.npmjs.com/package/mqtt.

Usage example:

```
var client = MQTT.connect('mqtt://test.mosquitto.org');

client.on('connect', function() {
   client.subscribe('/foo');
   client.publish('/bar', 'Hello mqtt');
});

client.on('message', function(topic, message) {
   console.log("got", message);
   client.publish("/baz", message);
});
```

=== GPIO

`GPIO.setmode(pin, mode, pull) -> true or false`::
  Set pin mode. 'mode' is number,  0 enables both input and output, 1 enables input only, 2 enabled output only, 3 enables interruptions on pin, see `GPUI.setisr`. `pull` is a number, 0 leaves pin floating, 1 connects pin to internal pullup resistor, 2 connects pin to internal pulldown resistor.
`GPIO.read(pin_num) -> 0 or 1`::
  Return GPIO pin level
`GPIO.write(pin_num, true_or_false) -> true of false`::
  Set a given pin
  to `true` or `false`, return false if paramaters are incorrect
`GPIO.setisr(pin, isr_type, func) -> true or false`::
  Assign interrruption handler for pin. `isr_type` is a number:
  * 0 disables interrupts
  * 1 enables interupts on positive edge
  * 2 - on negative edge
  * 3 - on any edge
  * 4 - on low level
  * 5 - on high level
  * 6 - button mode +
  `func` is callback to be called on interrupt, its prototype is `function myisr(pin, level)`. See link:https://github.com/cesanta/smart.js/blob/master/platforms/esp8266/fs/gpio.js[button helper] for `button mode` usage example.

=== ADC

`ADC.read(pin) -> number`::
  Return raw reading of the ADC device for a given analog input pin.

`ADC.readVoltage(pin) -> number`::
  Read a voltage from the analog pin. Please read the platform specific manual for how to calibrate.

Example:

[source,js]
----
function adcExample() {
  print("ADC:", ADC.read(0));
  setTimeout(adcExample, 1000);
}
----

=== SPI

`var spi = new SPI()`::
  SPI constructor
`spi.tran(dataToSend, [bytesToRead, command, address]) -> number`::
  Send and receive data within one transaction. `dataToSend` is a
  32bit number to send to SPI. `bytesToRead` is a number of bytes to read
  from SPI (1-4). If device requires explicit command and address, they
  might be provided via `command` and `address` parameters.
`spi.txn(commandLenBits, command, addrLenBits, address, dataToSendLenBits, dataToWrite, dataToReadLenBits, dummyBits) -> number`::
  Send and receive data within one transaction. The same as `spi.tran`, but allows to use arbitrary (1-32 bits) lengths. This function should be used if device requires, for example, 9bit data, 7bit address, 3bit command etc.

There is a detailed description in link:https://github.com/cesanta/smart.js/blob/master/src/sj_spi_js.c[sj_spi_js.c].

See link:https://github.com/cesanta/smart.js/blob/master/platforms/esp8266/fs/MPL115A1.js[barometer driver] for the usage example.

=== I2C

Constants:

`I2C.READ`, `I2C.WRITE`::
  Communication mode constants
`I2C.ACK`, `I2C.NAK`, `I2C.NONE`::
  Acknowledgement types
`var i2c = new I2C(sda_gpio, scl_gpio)`::
  An I2C constructor

Low-level API:

`i2c.start(addr, mode) -> ackType`::
  Claims the bus, puts the slave address on it and reads ack/nak. addr is the 7-bit address (no r/w bit), mode is either `I2C.READ` or `I2C.WRITE`.
`i2c.stop()`::
  Put stop condition on the bus and release it.
`i2c.send(data) -> ackType`::

  Send data to the bus. If `data` is a number between 0 and 255, a single byte is sent. If `data` is a string, all bytes from the string are sent. Return value is the acknowledgement sent by the receiver. When a multi-byte sequence (string) is sent, all bytes must be positively acknowledged by the receiver, except for the last one. Acknowledgement for the last byte becomes the return value. If one of the bytes in the middle was not acknowledged, `I2C.ERR` is returned.
`i2c.readByte([ackType]) -> number`::
  Read a byte from the slave and `ACK`/`NAK` as instructed. The argument is optional and defaults to `ACK`. It is possible to specify `NONE`, in which case the acknoewledgment bit is not transmitted, and the call must be followed up by `sendAck`.
`i2c.readString(n, [lastAckType]) -> string`::
  Read a sequence of `n` bytes. Ann bytes except the last are `ACK`-ed, `lastAckType` specifies what to do with the last one and works like `ackType` does for `readByte`.
`i2c.sendAck(ackType)`::
  Send an acknowledgement. This method must be used after one of the
  `read` methods with `NONE` ack type.

High-level API:

`i2c.read(addr, nbytes) -> string or I2C.ERR`::
  Issue a read request to the device with address `addr`,
  reading `nbytes` bytes. Acknowledges all incoming bytes except the last one.
`i2c.write(addr, data) -> ackType`::
  Issue a write request to the device with address `addr`.
  `data` is passed as is to `.send` method.
`i2c.do(addr, req, ...) -> array`::
  Issues multiple requests to the same device, generating repeated start
  conditions between requests. Each request is an array with 2 or 3 elements:
  `[command, num_bytes, opt_param]`.
  `command` is `I2C.READ` or `I2C.WRITE` for read or write respectively,
  `num_bytes` is a number of bytes for read request or data to send for
  write request, `opt_param` is optional, has different meaning for different
  types of requests: for read requests, it's
  `ackType` for the last read byte (defaults to `I2C.NAK`), and for write
  requests, `ackType` to expect from the device after last sent byte
  (defaults to `I2C.ACK`). +
  Return value is an array that contains the one element for each request on
  success (string data for reads, `ackType` for writes), or possibly less than
  that on error, in which case last element will be `I2C.ERR`. Errors include:
    ** Address wasn't ACK'ed (no such device on the bus).
    ** Device sent NACK before all the bytes were written.
    ** `ackType` for the last byte written doesn't match what was expected.

There is a detailed description of this API in
link:https://github.com/cesanta/smart.js/blob/master/src/sj_i2c_js.c[sj_i2c_js.c].
See link:https://github.com/cesanta/smart.js/blob/master/platforms/esp8266/fs/MCP9808.js[temperature sensor driver]
and https://github.com/cesanta/smart.js/blob/master/platforms/esp8266/fs/MC24FC.js[EEPROM driver]
for usage example.

=== PWM

`PWM.set(pin, period, duty)`::
  - `pin`: GPIO number.
  - `period`: Period, in microseconds. 20 is the shortest supported and any number given will be rounded down to the nearest multiple of 10. `period = 0` disables PWM on the pin (`duty = 0` is similar but does not perform internal cleanup).
  - `duty`: How many microseconds to spend in "1" state. Must be between `0` and `period` (inclusive). `duty = 0` is "always off", `duty = period` is "always on", `period / 2` is a square wave. Number will be rounded down to the nearest multiple of 10.

=== UART

ESP8266 is equipped with two identical UART modules, `0` and `1` (but UART1's `RX` pin cannot be used due to conflicts with SPI flash, so it's effectively transmit-only).
JavaScript API consists of a top-level `UART` function, which takes one argument,
module number, and returns an object that can be used to manipulate it:

`var u = UART(0);`

This object has the following methods:

`configure({configuration}) -> bool`::
  - `configuration`: Optional object with zero or more of the following fields:
    - `baud_rate`: Baud rate to use [default: `115200`].
    - `rx_buf_size`: Size of the receive buffer [`256`].
    - `rx_fc_ena`: Enable hardware receive flow control (RTS) [`false`].
    - `tx_buf_size`: Transmit buffer size [`256`].
    - `tx_fc_ena`: Enable hardware transmit full control (CTS) [`false`].
    - `swap_rxcts_txrts`: Swap `RX`/`CTS` and `TX`/`RTS` pins [`false`].

All fields are optional and defaults will be used for the missing ones.

Note: After configuration, UART receive interrupt is disabled and need to be either explicitly via `setRXEnabled` or implicitly by installing `onRecv` event handler.

`recv([max]) -> string`:
    - `max`: Optional maximum number of bytes to receive. If not specified, will return as much as possible from the receive buffer.

Note: return value less than `max` does not necessarily mean no more data is available. Only empty return value is an indication of an empty buffer.

`setRXEnabled(enabled)`:
    - `enabled`: If `false`, receiver will be throttled - no more receive events will be delivered and if hardware receive flow control is on, the `RTS` pin will be deactivated.

`sendAvail() -> number`:
    Returns the available space in send buffer.

`send(data) -> number`:
    Returns number of bytes of input data consumed.
    - `data`: A string to be sent. Up to `sendAvail()` bytes will be put into transmit buffer.

Event handlers:

`onRecv(cb, [disable_rx])`:
    `cb` will be invoked when more data is available for reading. `cb` does not take any arguments, and should consume data using `recv`. Moreover, no more callbacks will be delivered until `recv` is invoked.

Note: `onRecv` will enable receive interrupts. If that is not desirable, a second argument with true value should be passed.

`onTXEmpty(cb)`:
    `cb` will be invoked when transmit buffer is empty. note that this does not
    include UART FIFO and thus there may be up to 128 bytes still to be put on
    the wire. At present there is no way to query transmit FIFO length.


Example:

[source,js]
----
// UART echo.
function doEcho(u) {
  var d, n;
  while (true) {
    n = u.sendAvail();
    if (n == 0) break;
    d = u.recv(n);
    if (!d) break;
    u.send(d);
  }
}

var u = UART(0);
u.configure({
  baud_rate: 115200,
  rx_buf_size: 1024,
  tx_buf_size: 1024,
});
u.onRecv(function() { doEcho(this); });
u.onTXEmpty(function() { doEcho(this); });
----

=== Watchdog timer (esp8266)

ESP8266 includes a watchdog timer, a mechanism designed to deal with software
lockups. This timer is periodically reset by the OS, or can be explicitly
"fed" by user code. Failure to do so will cause the device to be reset.
The current default watchdog timer period is about 1 minute.

`Sys.wdtFeed()`:: delay restart of the device for 1 minute. This function
  has to be called inside long loops, or other long operations to
  prevent device reset.

=== Wifi

By default, Wifi module enables access point mode, and acts as a
DHCP server for it.

`Wifi.setup("yourssid", "youpassword") -> true or false`:: Connect
  to the local Wifi network
`Wifi.status() -> status_string`:: Check current Wifi status
`Wifi.ip() -> ip_address_string`:: Get assigned IP address.
  `Wifi.ip(1)` returns IP address of the access point interface.
`Wifi.show()`:: Returns the current SSID
`Wifi.changed(cb)`:: Invokes `cb` whenever the connection status changes:
  - 0: connected
  - 1: disconnected
  - 2: authmode changed
  - 3: got ip
  - 4: client connected to ap
  - 5: client disconnected from ap
`Wifi.mode(mode) -> true or false`:: Set Wifi mode. `mode` is a number,
  1 is station, 2 is soft-AP, 3 is station + soft-AP
`Wifi.scan(cb)`:: Invoke `cb` with a list of discovered networks.

=== Cloud

This interface provides an easy way to send data to the
[Cesanta cloud](https://cloud.cesanta.com/). On a cloud side, it is easy to build interactive
real-time dashboards.

`Cloud.store(name, value [, options]) -> undefined`:: Store metric `name`
with value `value` in a cloud storage. Optional `options` object can be
used to specify metrics labels and success callback function. Example:
`Cloud.store('temperature', 36.6)`. The following prerequisites has
to be met:
  - Wifi needs to be configured
  - Global configuration object `conf` needs to have device ID and
  password set, `conf.dev.id` and `conf.dev.psk`
  - Device with those ID and PSK needs to be registered in a cloud - see
    video at the top of this document

=== Built-in functions

`usleep(num_microseconds) -> undefined`:: Sleep for `num_microseconds`
`dsleep(num_microseconds [, dsleep_option]) -> undefined`:: Deep sleep for
  `num_microseconds`. If `dsleep_option` is specified, ESP's
  `system_deep_sleep_set_option(dsleep_option)` is called prior to going to
  sleep. The most useful seems to be 4 (keep RF off on wake up,
  reduces power consumption).
`setTimeout(callback, num_milliseconds) -> undefined`:: Schedule
  function call after `num_milliseconds`.
`print(arg1, ...) -> undefined`:: Stringify and print
  arguments to the command prompt
`GC.stat() -> stats_object`:: Return current memory usage
`Debug.mode(mode) -> status_number`:: Set redirection for system
  and custom (stderr) error logging: `Debug.OFF` or `0` = /dev/null;
  `Debug.OUT` or `1` = uart0, `Debug.ERR` or `2` = uart1
`Debug.print(...)`::
  Print information to current debug output (set by `Debug.mode`)


=== Sys

`Sys.time() -> number`:: Returns system time, as a floating point number, in seconds.

=== OTA (Over-the-air programming)

Smart.js OTA is designed to work in either unattended or controllable mode.

By default the updater module starts in unattended mode. Which means, it will initiate the update
process immediately after receiving a command from server. After a successful update, the device
will be rebooted to use new firmware.

When in controllable mode, the updater invokes a callback on different stages of the update process.
The callback can be set with the `Sys.updater.notify()` function; its prototype is `function (event, params)`.
When the updater gets an incoming request, the callback receives `Sys.updater.GOT_REQUEST` and `params` contains URL of the new firmware
manifest file. The callback handler can either start the update process with `Sys.updater.start(url)` function
or delay this process, storing the provided URL and calling `Sys.updater.start(url)` later.

Once the update process is finished, the callback receives one of the following events:

- `Sys.updater.NOTHING_TODO`: the device is already running newest firmware.
- `Sys.updater.FAILED`: update cannot be completed, callback handler can try to repeat updating by invoking Sys.updater.start(url) again.
- `Sys.updater.COMPLETED`: update process completed successfully. The callback handler can reboot the device with
  `Sys.exit()` to use new firmware immediately or delay reboot until suitable moment.

Example:
```
function upd(ev, url) {
   if (ev == Sys.updater.GOT_REQUEST) {
      print("Starting update from", url);
      Sys.updater.start(url);
   }  else if(ev == Sys.updater.NOTHING_TODO) {
      print("No need to update");
   } else if(ev == Sys.updater.FAILED) {
      print("Update failed");
   } else if(ev == Sys.updater.COMPLETED) {
     print("Update completed");
     Sys.reboot();
   }
}

Sys.updater.notify(upd);
```
