FROM ubuntu:xenial

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -q \
      apt-utils autoconf bison build-essential flex gawk git gperf help2man \
      libexpat-dev libncurses5-dev libtool-bin \
      python python-dev python-git python-pyelftools python-serial python-six python-yaml \
      software-properties-common texinfo unzip vim-nox wget zile zip && \
    apt-get clean

RUN cd /tmp && \
    git clone https://github.com/rojer/fsync-stub && \
    cd /tmp/fsync-stub && ./install.sh && \
    rm -rf /tmp/fsync-stub

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -q \
      gcc-arm-none-eabi gdb-arm-none-eabi libnewlib-arm-none-eabi libnewlib-dev && \
    apt-get clean

# STM32Cube can be found at http://www.st.com/en/development-tools/stm32cubemx.html#getsoftware-scroll
# and pruned a bit by removing some heavy, but non-essential stuff:
# rm -rf Middlewares/ST Middlewares/Third_Party/mbedTLS Projects Utilities
ADD STM32Cube_FW_F7_V1.8.0.tar.xz /opt
ADD lwipopts.patch /opt
RUN cd /opt/STM32Cube_FW_F7_V1.8.0 && patch -p 0 < ../lwipopts.patch

ADD fw_meta.py serve_core.py mkspiffs mkspiffs8 /usr/local/bin/

ENV STM32CUBE_F7_PATH /opt/STM32Cube_FW_F7_V1.8.0
ENV MGOS_TARGET_GDB /usr/bin/arm-none-eabi-gdb
