FROM ubuntu:xenial

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -q \
      apt-utils autoconf bison build-essential flex gawk git gperf help2man \
      libexpat-dev libncurses5-dev libtool-bin \
      python python-dev python-git python-pyelftools python-serial python-six python-yaml \
      software-properties-common texinfo unzip vim-nox wget zile zip && \
    apt-get clean

RUN cd /tmp && \
    git clone https://github.com/rojer/fsync-stub && \
    cd /tmp/fsync-stub && ./install.sh && \
    rm -rf /tmp/fsync-stub

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -q \
      gcc-arm-none-eabi gdb-arm-none-eabi libnewlib-arm-none-eabi libnewlib-dev && \
    apt-get clean

ARG STM32CUBE_F4_DIR
ADD tmp/$STM32CUBE_F4_DIR /opt/$STM32CUBE_F4_DIR
ENV STM32CUBE_F4_PATH /opt/$STM32CUBE_F4_DIR

ARG STM32CUBE_F7_DIR
ADD tmp/$STM32CUBE_F7_DIR /opt/$STM32CUBE_F7_DIR
ENV STM32CUBE_F7_PATH /opt/$STM32CUBE_F7_DIR

ADD fw_meta.py serve_core.py mkspiffs mkspiffs8 /usr/local/bin/

ENV MGOS_TARGET_GDB /usr/bin/arm-none-eabi-gdb
